Repository iquizoo/reports, pull requests merged in 2018-06, with the labels that each got.

#6 Add texts for report
  config.yml
Labels: Feature, enhancement

#18 Revisions of all the reports
  .gitignore
  .travis.yml
  _bookdown.yml
  assets/db/daxing.xlsx
  assets/image/model.jpg
  assets/template/body.glue.Rmd
  assets/template/body.glue.district.Rmd
  build.R
  config/body.daxing.district.Rmd
  config/body.daxing.school.Rmd
  config/body.lishui.one.Rmd
  config/context.daxing.district.Rmd
  config/context.daxing.school.Rmd
  config/context.lishui.one.Rmd
  config/descriptions.daxing.district.yml
  config/descriptions.daxing.school.yml
  config/descriptions.district.yml
  config/descriptions.lishui.one.yml
  config/descriptions.yml
  config/params.yml
  config/report.map.yml
  index.Rmd
  scripts/prepare.R
  scripts/utils.R
Labels: bug, enhancement

#26 CLI options enhancement
  build.R
  config/report.map.yml
  scripts/utils.R
Labels: enhancement
